package lens

import (
	"encoding/hex"
	"fmt"
	"reflect"
	"sort"
	"strconv"
	"strings"
)

// Kind classifies a Node in the neutral tree.
type Kind uint8

const (
	// KindScalar is a leaf value: number, string, bool, enum name, hex blob.
	KindScalar Kind = iota
	// KindStruct is a named record with ordered fields.
	KindStruct
	// KindList is an ordered sequence of values.
	KindList
)

func (k Kind) String() string {
	switch k {
	case KindScalar:
		return "scalar"
	case KindStruct:
		return "struct"
	case KindList:
		return "list"
	default:
		return "unknown"
	}
}

// Node is the neutral, format-independent representation of a decoded XDR
// value. Every formatter and the differ consume Node trees rather than the
// concrete xdr.* Go types, which keeps rendering and diffing decoupled from
// the 400-odd generated XDR structs.
//
// A Node is a tree: Children is populated for KindStruct and KindList, and
// Value is populated for KindScalar.
type Node struct {
	// Name is the field name within the parent. Empty at the root and for
	// list elements (which are addressed by index).
	Name string
	// Kind determines whether Value or Children carries the payload.
	Kind Kind
	// TypeName is the originating XDR type, e.g. "TransactionEnvelope".
	// It is best-effort and may be empty for anonymous values.
	TypeName string
	// Value holds the payload for KindScalar. It is one of: string, bool,
	// int64, uint64, or float64, so that formatters need no reflection.
	Value any
	// Note carries a human-friendly rendering derived by an enricher, such
	// as a strkey address or a formatted amount. Formatters show it
	// alongside the raw Value.
	Note string
	// Children holds the members of a struct or the elements of a list.
	Children []*Node
}

// IsZero reports whether the node carries no meaningful payload.
func (n *Node) IsZero() bool {
	return n == nil || (n.Kind == KindScalar && n.Value == nil && n.Note == "")
}

// Child returns the first direct child with the given name, or nil.
func (n *Node) Child(name string) *Node {
	if n == nil {
		return nil
	}
	for _, c := range n.Children {
		if c.Name == name {
			return c
		}
	}
	return nil
}

// Find walks a dotted path such as "Result.Results[0].Code" and returns the
// node at that location, or nil when the path does not resolve.
func (n *Node) Find(path string) *Node {
	cur := n
	for _, seg := range splitPath(path) {
		if cur == nil {
			return nil
		}
		if seg.index >= 0 {
			if seg.name != "" {
				cur = cur.Child(seg.name)
				if cur == nil {
					return nil
				}
			}
			if seg.index >= len(cur.Children) {
				return nil
			}
			cur = cur.Children[seg.index]
			continue
		}
		cur = cur.Child(seg.name)
	}
	return cur
}

// String renders the scalar payload for display. Struct and list nodes render
// as a short type summary rather than their full contents.
func (n *Node) String() string {
	if n == nil {
		return "<nil>"
	}
	switch n.Kind {
	case KindScalar:
		if n.Value == nil {
			return n.Note
		}
		s := fmt.Sprintf("%v", n.Value)
		if n.Note != "" {
			return s + " (" + n.Note + ")"
		}
		return s
	case KindList:
		return fmt.Sprintf("[%d item(s)]", len(n.Children))
	default:
		if n.TypeName != "" {
			return n.TypeName
		}
		return "{...}"
	}
}

// maxDepth bounds the tree walk. XDR itself is decoded with the SDK's own
// depth limit, so this is a second belt-and-braces guard against a
// pathological value producing an unbounded walk.
const maxDepth = 200

// buildNode converts an arbitrary decoded XDR value into a neutral Node tree.
//
// This function, and the enricher lookup it calls, are the only places in the
// project that use reflection. Everything downstream — formatters, the
// differ, explain — operates on Node. Keeping the reflection confined here is
// deliberate: adding a new output format never requires touching reflect.
func buildNode(name string, rv reflect.Value, depth int) *Node {
	if depth > maxDepth {
		return &Node{Name: name, Kind: KindScalar, Value: "<max depth exceeded>"}
	}

	// Unwrap pointers and interfaces. A nil pointer means an absent union arm
	// or optional field, which we prune entirely rather than render as null.
	for rv.Kind() == reflect.Pointer || rv.Kind() == reflect.Interface {
		if rv.IsNil() {
			return nil
		}
		rv = rv.Elem()
	}
	if !rv.IsValid() {
		return nil
	}

	typeName := rv.Type().Name()

	// A registered enricher wins over the generic rendering: this is how
	// AccountId becomes G..., Asset becomes CODE:ISSUER, and so on.
	if note, raw, ok := enrich(rv); ok {
		return &Node{Name: name, Kind: KindScalar, TypeName: typeName, Value: raw, Note: note}
	}

	// Named enum types carry a String() method generated by the XDR
	// toolchain. Using it turns "Code: -13" into a readable constant name,
	// which is most of the value of the tool.
	if s, ok := stringerName(rv); ok {
		return &Node{Name: name, Kind: KindScalar, TypeName: typeName, Value: s}
	}

	switch rv.Kind() {
	case reflect.Struct:
		n := &Node{Name: name, Kind: KindStruct, TypeName: typeName}
		rt := rv.Type()
		for i := range rv.NumField() {
			f := rt.Field(i)
			if f.PkgPath != "" { // unexported
				continue
			}
			child := buildNode(f.Name, rv.Field(i), depth+1)
			if child == nil {
				continue
			}
			// Amount formatting depends on the field name, not just the
			// type, so it is applied here rather than in the type registry.
			if note, ok := enrichAmountField(f.Name, rv.Field(i)); ok {
				child.Note = note
			}
			n.Children = append(n.Children, child)
		}
		return n

	case reflect.Slice, reflect.Array:
		// Byte sequences are hashes, signatures and keys. Rendering them as
		// a list of 32 integers is useless, so they become hex scalars.
		if rv.Type().Elem().Kind() == reflect.Uint8 {
			b := byteSlice(rv)
			if rv.Kind() == reflect.Slice && rv.IsNil() {
				return nil
			}
			return &Node{
				Name:     name,
				Kind:     KindScalar,
				TypeName: typeName,
				Value:    hex.EncodeToString(b),
				Note:     printableASCII(b),
			}
		}
		if rv.Kind() == reflect.Slice && rv.IsNil() {
			return nil
		}
		n := &Node{Name: name, Kind: KindList, TypeName: typeName}
		for i := range rv.Len() {
			child := buildNode("", rv.Index(i), depth+1)
			if child == nil {
				child = &Node{Kind: KindScalar, Value: nil}
			}
			n.Children = append(n.Children, child)
		}
		return n

	case reflect.Map:
		n := &Node{Name: name, Kind: KindStruct, TypeName: typeName}
		keys := rv.MapKeys()
		sort.Slice(keys, func(i, j int) bool {
			return fmt.Sprintf("%v", keys[i]) < fmt.Sprintf("%v", keys[j])
		})
		for _, k := range keys {
			child := buildNode(fmt.Sprintf("%v", k), rv.MapIndex(k), depth+1)
			if child == nil {
				continue
			}
			n.Children = append(n.Children, child)
		}
		return n

	case reflect.Bool:
		return &Node{Name: name, Kind: KindScalar, TypeName: typeName, Value: rv.Bool()}

	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return &Node{Name: name, Kind: KindScalar, TypeName: typeName, Value: rv.Int()}

	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return &Node{Name: name, Kind: KindScalar, TypeName: typeName, Value: rv.Uint()}

	case reflect.Float32, reflect.Float64:
		return &Node{Name: name, Kind: KindScalar, TypeName: typeName, Value: rv.Float()}

	case reflect.String:
		return &Node{Name: name, Kind: KindScalar, TypeName: typeName, Value: rv.String()}

	default:
		return &Node{Name: name, Kind: KindScalar, TypeName: typeName, Value: fmt.Sprintf("%v", rv)}
	}
}

// byteSlice extracts bytes from a slice or array value without assuming the
// value is addressable (arrays inside structs obtained by value are not).
func byteSlice(rv reflect.Value) []byte {
	if rv.Kind() == reflect.Slice {
		return rv.Bytes()
	}
	b := make([]byte, rv.Len())
	for i := range rv.Len() {
		b[i] = byte(rv.Index(i).Uint())
	}
	return b
}

// printableASCII returns the string form of b when it is entirely printable
// ASCII, which makes asset codes and text memos readable. Otherwise it
// returns "" and the caller shows hex alone.
func printableASCII(b []byte) string {
	if len(b) == 0 || len(b) > 64 {
		return ""
	}
	trimmed := strings.TrimRight(string(b), "\x00")
	if trimmed == "" {
		return ""
	}
	for _, r := range trimmed {
		if r < 0x20 || r > 0x7e {
			return ""
		}
	}
	return strconv.Quote(trimmed)
}

type pathSeg struct {
	name  string
	index int
}

// splitPath parses "a.b[2].c" into segments. An index of -1 means the segment
// addresses a named field rather than a list element.
func splitPath(path string) []pathSeg {
	var segs []pathSeg
	for _, part := range strings.Split(path, ".") {
		if part == "" {
			continue
		}
		name := part
		for {
			open := strings.IndexByte(name, '[')
			if open < 0 {
				if name != "" {
					segs = append(segs, pathSeg{name: name, index: -1})
				}
				break
			}
			closeIdx := strings.IndexByte(name[open:], ']')
			if closeIdx < 0 {
				segs = append(segs, pathSeg{name: name, index: -1})
				break
			}
			closeIdx += open
			idx := 0
			if _, err := fmt.Sscanf(name[open+1:closeIdx], "%d", &idx); err != nil {
				idx = -1
			}
			segs = append(segs, pathSeg{name: name[:open], index: idx})
			name = name[closeIdx+1:]
			if name == "" {
				break
			}
		}
	}
	return segs
}

// stringerName returns the String() rendering for named integer types, which
// is how the generated XDR enums expose their constant names. It deliberately
// does not fire for plain numeric types like Uint32 or Int64, whose String()
// output would be no more informative than the number itself.
func stringerName(rv reflect.Value) (string, bool) {
	t := rv.Type()
	if t.Name() == "" || t.PkgPath() == "" {
		return "", false
	}
	switch t.Kind() {
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
	default:
		return "", false
	}
	if !isEnumType(t) {
		return "", false
	}
	s, ok := rv.Interface().(fmt.Stringer)
	if !ok {
		return "", false
	}
	name := safeString(s)
	if name == "" {
		return "", false
	}
	return name, true
}

// safeString calls String() while tolerating a panic. Generated XDR helpers
// can dereference union arms that are absent in a malformed value, and this
// tool is expected to survive hostile input rather than crash on it.
func safeString(s fmt.Stringer) (out string) {
	defer func() {
		if r := recover(); r != nil {
			out = ""
		}
	}()
	return s.String()
}
